using System;
using System.Collections.Generic;
using FSP.Domain.Common;
using FSP.Domain.Events;

namespace FSP.Domain.Entities;

public enum WorkOrderStatus
{
    Draft = 0,
    Assigned = 1,
    InProgress = 2,
    Completed = 3,
    Cancelled = 4
}

public enum WorkOrderPriority
{
    Low = 0,
    Medium = 1,
    High = 2,
    Critical = 3
}

/// <summary>
/// WorkOrder Aggregate Root. Enforces factory creation, idempotency, and concurrency tokens per ADR-002.
/// </summary>
public class WorkOrder : BaseTenantEntity
{
    private readonly List<WorkOrderAttachment> _attachments = new();

    public string Title { get; private set; } = string.Empty;
    public string Description { get; private set; } = string.Empty;
    public WorkOrderStatus Status { get; private set; }
    public WorkOrderPriority Priority { get; private set; }
    public Guid? AssignedTechnicianId { get; private set; }
    
    /// <summary>
    /// Idempotency and deduplication key generated by mobile client when offline per DEC-WO-002.
    /// </summary>
    public Guid ClientReferenceId { get; private set; }

    /// <summary>
    /// EF Core RowVersion token for optimistic concurrency verification per DEC-WO-004.
    /// </summary>
    public byte[] RowVersion { get; private set; } = Array.Empty<byte>();

    public IReadOnlyCollection<WorkOrderAttachment> Attachments => _attachments.AsReadOnly();

    private WorkOrder() : base() { }
    private WorkOrder(Guid tenantId, Guid createdBy) : base(tenantId, createdBy) { }

    public static WorkOrder Create(
        Guid tenantId, 
        string title, 
        string description, 
        WorkOrderPriority priority, 
        Guid clientReferenceId,
        Guid createdBy)
    {
        if (string.IsNullOrWhiteSpace(title))
            throw new ArgumentException("WorkOrder title cannot be empty.", nameof(title));

        var workOrder = new WorkOrder(tenantId, createdBy)
        {
            Title = title,
            Description = description,
            Priority = priority,
            Status = WorkOrderStatus.Draft,
            ClientReferenceId = clientReferenceId == Guid.Empty ? Guid.NewGuid() : clientReferenceId
        };

        workOrder.AddDomainEvent(new WorkOrderCreatedDomainEvent(workOrder.Id, tenantId, title, createdBy));

        return workOrder;
    }

    public void AssignTechnician(Guid technicianId, Guid modifiedBy)
    {
        if (technicianId == Guid.Empty)
            throw new ArgumentException("Technician ID cannot be empty.", nameof(technicianId));

        AssignedTechnicianId = technicianId;
        Status = WorkOrderStatus.Assigned;
        LastModifiedAtUtc = DateTime.UtcNow;
        LastModifiedBy = modifiedBy;

        AddDomainEvent(new WorkOrderAssignedDomainEvent(Id, TenantId, technicianId, modifiedBy));
    }

    public void AddAttachment(WorkOrderAttachment attachment)
    {
        if (attachment == null) throw new ArgumentNullException(nameof(attachment));
        _attachments.Add(attachment);
    }
}
